version: '3.8'

services:
  dxf-reader-api:
    container_name: dxf-reader
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    volumes:
      - .:/dxf-reader
    command: uvicorn rest.server:app --reload --workers 1 --host 0.0.0.0 --port 8080
#    env_file:
#      - ./env
    ports:
      - 8080:8080
